FROM nginx
COPY ./default.conf /etc/nginx/conf.d/default.conf
# The default.conf file is a custom configuration file that we are going to use to overwrite the default configuration file that comes with the NGINX image.